name: End-to-End Testing
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    name: Run cypress Test
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Start development server
        run: npm run dev
      - uses: cypress-io/github-action@v6
      - name: Start development server
        run: npm run dev
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`