# Name of the workflow as it will appear in the GitHub Actions UI
name: End-to-end tests

# Define the events that will trigger the workflow
on: 
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

# Define the jobs to be run as part of the workflow
jobs:
  cypress-run:
    # Specify the type of machine to run the job on
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    # Define the sequence of steps to execute in the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Check out the repository code so the workflow can access it

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Set up the Node.js environment
        with:
          node-version: '16'  # Specify the Node.js version to use

      - name: Install dependencies
        run: npm install  # Install the project's npm dependencies

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6  # Use the Cypress GitHub Action to run tests
        with:
          record: false  # Do not record the test results to the Cypress Dashboard
          start: npm run dev  # Command to start the application before running tests
          wait-on: http://localhost:3000  # Wait for the application to be available at this URL
          wait-on-timeout: 60  # Maximum time to wait for the application to start (in seconds)

      # Additional Steps for Future Reference

      # - name: Lint Code
      #   run: npm run lint  # Run a linter to check for code style issues

      # - name: Run Unit Tests
      #   run: npm test  # Execute unit tests to ensure code correctness

      # - name: Build Application
      #   run: npm run build  # Build the application for production

      # - name: Notify Team
      #   uses: slackapi/slack-github-action@v1.15.0
      #   with:
      #     channel-id: 'C12345678'  # Slack channel ID
      #     text: 'CI pipeline completed successfully!'  # Notification message